openapi: 3.0.0
info:
  title: Marketplace API
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Development server

paths:
  /api/marketplace/event:
    post:
      summary: Create a marketplace event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarketplaceEvent'
      responses:
        201:
          description: Marketplace event created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketplaceEvent'

components:
  schemas:
    MarketplaceEvent:
      type: object
      properties:
        raw:
          type: array
          items:
            type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
        totalResults:
          type: integer

    Item:
      type: object
      properties:
        raw:
          type: array
          items:
            type: integer
        offerId:
          type: integer
        isTradable:
          type: integer
        isTradableReadable:
          type: string
        type:
          type: integer
        typeReadable:
          type: string
        spriteId:
          type: integer
        itemName:
          type: string
        price:
          type: integer
        timeLeft:
          type: integer
        average:
          type: integer
        amount:
          type: integer

    /api/user/{userId}/rooms:
    get:
      summary: List user's rooms
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successfully retrieved user's rooms
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'

  /api/room/{roomId}/furniture:
    get:
      summary: Get room's furniture contents
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successfully retrieved room furniture
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Furniture'

  /api/room/{roomId}/details:
    post:
      summary: Receive data about a room
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoomDetails'
      responses:
        201:
          description: Successfully received room data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomDetails'

  components:
    schemas:
      Room:
        type: object
        properties:
          id:
            type: string
            description: Room ID
          name:
            type: string
            description: Room name

      Furniture:
        type: object
        properties:
          id:
            type: string
            description: Furniture ID
          name:
            type: string
            description: Furniture name
          position:
            type: object
            properties:
              x:
                type: integer
              y:
                type: integer

      RoomDetails:
        type: object
        properties:
          owner:
            type: string
            description: The user ID of the room owner
          usersInRoom:
            type: array
            items:
              type: string
            description: A list of user IDs currently in the room
          furniture:
            type: array
            items:
              $ref: '#/components/schemas/Furniture'
            description: A list of furniture items in the room with their positions